// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqagjjzgwmhlgikawswb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxYWdqanpnd21obGdpa2F3c3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzA4NDEsImV4cCI6MjA2NTg0Njg0MX0.taFjljXk63E6PZEJZfE0QX6vX5r9CUKcYV5me15-yQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);